// <auto-generated />
using BlazorEcomerce.Server;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorEcomerce.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorEcomerce.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "La serie Epson LQ-590II ofrece la durabilidad y la facilidad de uso para requisitos críticos de impresión diaria.",
                            ImageUrl = "https://electronicapanamericana.com/wp-content/uploads/L3210.jpg",
                            Price = 3090m,
                            Title = "Epson, LQ-590II, Impresora Matriz De Punto Para Entornos De Impresión Exigentes"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Marca: Appple",
                            ImageUrl = "https://ishop.gt/cdn/shop/products/Sin_titulo_2_4c515b86-0190-4695-9343-fe1e0668e962_1200x.jpg?v=1669418179",
                            Price = 2899m,
                            Title = "Tablet Apple IPad 9, De 10.2 Pulgadas, 64GB, WiFi, Pantalla Retina, Multitouch"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Marca: Appple",
                            ImageUrl = "https://ishop.gt/cdn/shop/products/Sin_titulo_2_4c515b86-0190-4695-9343-fe1e0668e962_1200x.jpg?v=1669418179",
                            Price = 2899m,
                            Title = "Tablet Apple IPad 9, De 10.2 Pulgadas, 64GB, WiFi, Pantalla Retina, Multitouch"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Nintendo Switch combina la potencia de una consola para el hogar con la movilidad de una consola portátil. Una nueva era para los videojuegos que te ofrece nuevas maneras de jugar, donde quieras, como quieras, cuando quieras.",
                            ImageUrl = "https://assets.nintendo.com/image/upload/f_auto/q_auto/dpr_2.0/c_scale,w_400/ncom/en_US/switch/split-cta-system",
                            Price = 3324m,
                            Title = "Consola Nintendo Switch Neon Version 2, JoyCon Azul/Rojo"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
